### ISSUE TITLE
.Net Core 3.1  LoadUserDict 下，會出現 Unhandled exception. System.UnauthorizedAccessException: Access to the path 

### ISSUE THREAD

**Issue by donma** [anderscui/jieba.NET#76]
在.net core console 下

```C#

segmenter.LoadUserDict(AppDomain.CurrentDomain.BaseDirectory + @"custom_dict");

```

會出現

```
Unhandled exception. System.UnauthorizedAccessException: Access to the path 'C:\Users\donma\source\repos\JiebaPrac\JiebaPrac\bin\Debug\netcoreapp3.1\custom_dict' is denied.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at System.IO.File.InternalReadAllLines(String path, Encoding encoding)
   at System.IO.File.ReadAllLines(String path, Encoding encoding)
   at JiebaNet.Segmenter.JiebaSegmenter.LoadUserDict(String userDictFile)
   at JiebaPrac.Program.Main(String[] args) in C:\Users\donma\source\repos\JiebaPrac\JiebaPrac\Program.cs:line 17


```

如果是我用 .net framework 4.7 ASP.net Webform 下會正常

麻煩了，感謝幫助..

**Comment by suichuan** [comment]
代码贴出来

**Comment by donma** [comment]
抱歉 是我自己犯蠢 已經解決了
感謝您的回應 👍
